config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('nagoyameshi.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

nagoyameshi/urls.py
from django.urls import path
from . import views

app_name = 'nagoyameshi'
urlpatterns = [
    path('', views.index, name='index'),
    path('top/', views.top, name='top'),
    path('restaurant/<int:pk>', views.restaurant_detail, name='restaurant_detail'),
    path('restaurant/review_list/<int:pk>', views.review_list, name='review_list'),
    path('restaurant/review_form/<int:pk>', views.review_form, name='review_form'),
    path('restaurant/review_edit/<int:pk>', views.review_edit, name='review_edit'),
    path('restaurant/review_delete/<int:pk>', views.review_delete, name='review_delete'),
    path('restaurant/reservation_form/<int:pk>', views.reservation_form, name='reservation_form'),
    path('restaurant/reservation_delete/<int:pk>', views.reservation_delete, name='reservation_delete'),
    path('mypage/', views.mypage, name='mypage'),

    # サブスク関連
    path("checkout/", views.checkout, name="checkout"),
    path("success/", views.success, name="success"),
    path("portal/", views.portal, name="portal"),
    path("premium/", views.premium, name="premium"),
]

nagoyameshi/forms.py
from django import forms
from .models import Review, Reservation, Restaurant
from django.utils import timezone
from django.utils.timezone import localtime
from django.core.exceptions import ValidationError

class ReviewForm(forms.ModelForm):

    class Meta:
        model = Review
        fields = [ 'restaurant_id', 'user_id', 'number_of_stars', 'comment', 'visited_date' ]


class ReservationForm(forms.ModelForm):

    class Meta:
        model = Reservation
        fields = ['user_id', 'restaurant_id', 'reservation_datetime', 'number_of_persons', 'comment']

class RestaurantFloorPriceForm(forms.ModelForm):

    class Meta:
        model = Restaurant
        fields = ['floor_price']

class RestaurantMaximumPriceForm(forms.ModelForm):

    class Meta:
        model = Restaurant
        fields = ['maximum_price']

nagoyameshi/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q, Avg
from . import models, forms
from django.contrib.auth import get_user_model
User = get_user_model()
from django.contrib import messages
from datetime import datetime
from django.conf import settings
from django.urls import reverse_lazy
import stripe
stripe.api_key  = settings.STRIPE_API_KEY

# ===============================================
# index
# ===============================================
class IndexView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'nagoyameshi/index.html')

index = IndexView.as_view()

# ===============================================
# サブスク : 購入処理のセッションを生成
# ===============================================
class CheckoutView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):

        # セッションを作る
        checkout_session = stripe.checkout.Session.create(
            line_items=[
                {
                    'price': settings.STRIPE_PRICE_ID,
                    'quantity': 1,
                },
            ],
            payment_method_types=['card'],
            mode='subscription',
            success_url=request.build_absolute_uri(reverse_lazy("nagoyameshi:success")) + '?session_id={CHECKOUT_SESSION_ID}',
            cancel_url=request.build_absolute_uri(reverse_lazy("nagoyameshi:index")),
        )

        print(checkout_session['id'])

        return redirect(checkout_session.url)

checkout = CheckoutView.as_view()

# ===============================================
# サブスク : 購入処理の支払い状況を確認
# ===============================================
class SuccessView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):

        # パラメータにセッションIDがあるかチェック
        if "session_id" not in request.GET:
            print("セッションIDがありません。")
            return redirect("nagoyameshi:index")
        
        # セッションIDが有効であるかチェック
        try:
            checkout_session_id = request.GET['session_id']
            checkout_session = stripe.checkout.Session.retrieve(checkout_session_id)
        except:
            print("このセッションIDは無効です。")
            return redirect("nagoyameshi:index")
        
        print(checkout_session)

        # statusをチェック。未払いであれば拒否する。
        if checkout_session["payment_status"] != "paid":
            print("未払い")
            return redirect("nagoyameshi:index")
        
        print("支払い済み")

        # 有効であれば、セッションIDからカスタマーIDを取得しユーザーモデルに記録する。
        request.user.customer_id = checkout_session["customer"]
        request.user.save()

        print("有料会員登録しました！")
        return redirect("nagoyameshi:premium")

success = SuccessView.as_view()

# ===============================================
# サブスク : ポータルサイトへのリダイレクト
# ===============================================
class PortalView(LoginRequiredMixin, View):
    def get(self, request, *ards, **kwargs):

        if not request.user.customer_id:
            print("有料会員登録されていません")
            return redirect("nagoyameshi:index")
        
        portalSession = stripe.billing_portal.Session.create(
            customer = request.user.customer_id,
            return_url = request.build_absolute_uri(reverse_lazy("nagoyameshi:premium")),
            )

        return redirect(portalSession.url)

portal = PortalView.as_view()

# ===============================================
# サブスク : 有料会員登録ページ/有料会員ページ
# ===============================================
template_inactive = "nagoyameshi/premium_inactive.html"
template_active = "nagoyameshi/premium_active.html"
class PremiumView(View):
    def get(self, request, *args, **kwargs):
        # サブスクが無効なら非会員のページを表示
        if not check_subscription_state(request):
            return render(request, template_inactive)

        # 有効なら会員のページを表示
        return render(request, template_active)

premium = PremiumView.as_view()

# ===============================================
# top
# ===============================================
class TopView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):

        # クエリビルダを生成
        query = Q()

        # リクエストから検索条件を取得
        keyword = request.GET.get('keyword')
        selected_category = request.GET.get('category')

        # 検索キーワードがある場合、検索条件を追加
        if keyword:

            words = keyword.replace('　', ' ').split()

            for word in words:
                if word == '':
                    continue
                query &= Q(name__icontains=word)

        # カテゴリが指定されている場合、検索条件に追加
        if selected_category:
            query &= Q(category_id__name__exact=selected_category)
        
        # 下限価格が指定されている場合、検索条件に追加
        form = forms.RestaurantFloorPriceForm(request.GET)
        if form.is_valid():
            cleaned = form.clean()
            query &= Q(floor_price__gte=cleaned['floor_price'])

        # 下限価格が指定されている場合、検索条件に追加
        form = forms.RestaurantMaximumPriceForm(request.GET)
        if form.is_valid():
            cleaned = form.clean()
            query &= Q(maximum_price__lte=cleaned['maximum_price'])
        

        # 条件に合致する店舗を検索
        restaurants = models.Restaurant.objects.filter(query)
        
        context = {'restaurants': restaurants}
        return render(request, 'nagoyameshi/top.html', context)
    
top = TopView.as_view()

# ===============================================
# 店舗詳細
# ===============================================
class RestaurantDetailView(LoginRequiredMixin, View):
    def get(self, request, pk, *args, **kwargs):
        restaurant = models.Restaurant.objects.get(pk=pk)
        photos = models.RestaurantPhoto.objects.filter(restaurant_id=restaurant)
        favorite = models.Favorite.objects.filter(user_id=request.user, restaurant_id=restaurant).exists()
        context = {'restaurant': restaurant, 'photos':photos, 'favorite':favorite}

        return render(request, 'nagoyameshi/restaurant_detail.html', context)
    
    def post(self, request, pk, *args, **kwargs):
        '''
        お気に入り登録の処理
        '''
        # サブスクが無効なら非会員のページを表示
        if not check_subscription_state(request):
            return render(request, template_inactive)
        
        restaurant = models.Restaurant.objects.get(pk=pk)
        query = Q()
        query &= Q(user_id = request.user)
        query &= Q(restaurant_id = models.Restaurant.objects.get(pk=pk))
        favorite = models.Favorite.objects.filter(query)

        if favorite:
            # 登録されていれば削除し、お気に入り登録を解除
            favorite.delete()
            messages.info(request, 'お気に入り登録を解除しました')
        else:
            # 登録されていなければ、お気に入り登録する
            new_favorite = models.Favorite()
            new_favorite.restaurant_id = models.Restaurant.objects.get(pk=pk)
            new_favorite.user_id = request.user
            new_favorite.save()
            messages.info(request, 'お気に入りに登録しました')

        favorite = models.Favorite.objects.filter(user_id=request.user, restaurant_id=restaurant).exists()
        context = {'restaurant': restaurant, 'favorite':favorite}
        
        return render(request, 'nagoyameshi/restaurant_detail.html', context)

restaurant_detail = RestaurantDetailView.as_view()

# ===============================================
# 店舗ごとのレビュー一覧
# ===============================================
class ReviewListView(LoginRequiredMixin, View):
    def get(self, request, pk, *args, **kwargs):
        restaurant = models.Restaurant.objects.get(pk=pk)
        review_list = models.Review.objects.filter(restaurant_id=pk)
        context = {'restaurant':restaurant, 'review_list': review_list}
        return render(request, 'nagoyameshi/review_list.html', context)

review_list = ReviewListView.as_view()

# ===============================================
# レビューフォーム
# ===============================================
class ReviewFormView(LoginRequiredMixin, View):
    def get(self, request, pk, *args, **kwargs):
        # サブスクが無効なら非会員のページを表示
        if not check_subscription_state(request):
            return render(request, template_inactive)
        
        form = forms.ReviewForm()
        restaurant = models.Restaurant.objects.get(pk=pk)
        context = {'restaurant':restaurant, 'form': form}
        return render(request, 'nagoyameshi/review_form.html', context)
    
    def post(self, request, pk, *args, **kwargs):
        '''
        レビューの投稿処理
        '''
        # サブスクが無効なら非会員のページを表示
        if not check_subscription_state(request):
            return render(request, template_inactive)
        
        copied = request.POST.copy()
        copied['restaurant_id'] = models.Restaurant.objects.get(pk=pk)
        copied['user_id'] = request.user

        form = forms.ReviewForm(copied)

        print('======form======')
        print(form)

        if form.is_valid():
            # バリデーションOK
            print('投稿完了')
            form.save()
            messages.success(request, 'レビューを投稿しました')
            return redirect('nagoyameshi:review_list', pk=pk)
        
        else:
            # バリデーションNG
            restaurant = models.Restaurant.objects.get(pk=pk)
            context = {'restaurant': restaurant, 'form': form}
 
            # エラーメッセージ
            values = form.errors.get_json_data().values()
            for value in values:
                for v in value:
                    messages.error(request, v["message"])

            return render(request, 'nagoyameshi/review_form.html', context)

review_form = ReviewFormView.as_view()

# ===============================================
# レビュー編集
# ===============================================

templates/nagoyameshi/index.html
{% extends "base.html" %}
{% load static %}

{% block title %}NAGOYAMESHI{% endblock %}

{% block content %}

<section id="index-image">
<div id="index-carousel" class="carousel slide">

    <div class="carousel-inner">
        {# item1 #}
        <div class="carousel-item active">
            <img src="{% static 'nagoyameshi/img/top/misokatsu.jpg'%}" class="d-block w-100" alt="...">
            <div class="carousel-caption h-100 d-flex flex-column align-items-center">
                <p class="carousel_text">Welcome to <br>Nagoya!</p>
                <a class="carousel_btn btn btn-primary" href="{% url 'nagoyameshi:top' %}">店舗一覧</a>
            </div>
        </div>

        {# item2 #}
        <div class="carousel-item">
            <img src="{% static 'nagoyameshi/img/top/napolitan.jpg'%}" class="d-block w-100" alt="...">
            <div class="carousel-caption h-100 d-flex flex-column align-items-center">
                <p class="carousel_text">名古屋の<br>いちおしB級グルメを<br>ご紹介</p>
                <a class="carousel_btn btn btn-primary" href="{% url 'nagoyameshi:top' %}">店舗一覧</a>
            </div>
        </div>

        {# item3 #}
        <div class="carousel-item">
            <img src="{% static 'nagoyameshi/img/top/ten-musu.jpg'%}" class="d-block w-100" alt="...">
            <div class="carousel-caption h-100 d-flex flex-column align-items-center">
                <p class="carousel_text">無料の店舗検索と<br>便利なサブスクリプションプラン</p>
                <a class="carousel_btn btn btn-primary" href="{% url 'nagoyameshi:top' %}">店舗一覧</a>
            </div>
        </div>
    </div>

    <button class="carousel-control-prev bg-transparent border-0 z-3" type="button" data-bs-target="#index-carousel" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>

    <button class="carousel-control-next bg-transparent border-0 z-3" type="button" data-bs-target="#index-carousel" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
    
    
</div>
</section>
{% endblock %}

templates/nagoyameshi/mypage.html
{% extends "base.html" %}
{% load bootstrap %}
{% load static %}

{% block title %}マイページ{% endblock %}

{% block content %}
<h1>{{user.username}}さんのマイページ</h1>

<div class="container">
<div class="w-75 mx-auto">

{# ========== お気に入り ========== #}
<section class="mb-5">
    <h3 class="mypage_section"><i class="fas fa-caret-right mr-2"></i><span>お気に入り</span></h3>
    <div class="ml-4">
        {% if user.customer_id %}
        {# 有料会員ならお気に入り店舗を表示 #}
            <p>{{ favorites.count }}件</p>
            <ul>
                {% if favorites %}
                    <div class="row flex-row flex-nowrap overflow-auto">
                        {% for favorite in favorites %}
                            <div class="col-lg-4">
                            <div class="card h-100" style="width: 15rem;">
                                {# イメージは仮 #}
                                <img src="{% static 'nagoyameshi/img/top/misokatsu.jpg' %}" class="card-img-top" alt="">
                                <div class="card-body">
                                    <h5 class="card-title">{{ favorite.restaurant_id.name }}</h5>
                                    <a href="{% url "nagoyameshi:restaurant_detail" pk=favorite.restaurant_id.pk%}" class="btn btn-secondary">もっと見る</a>
                                </div>
                            </div>
                            </div>
                        {% endfor %}
                    </div>
                {% else %}
                    <p>お気に入り登録した店舗はまだありません。</p>
                {% endif %}
            </ul>
        {% else %}
        {# 無料会員なら有料会員登録に誘導 #}
            <p> <a href="{% url 'nagoyameshi:premium' %}">有料会員になる</a>と店舗をお気に入り登録することができます。</p>

        {% endif %}
    </div>
</section>

{# ========== 予約一覧 ========== #}
<section class="mb-5">
    <h3 class="mypage_section"><i class="fas fa-caret-right mr-2"></i><span>予約一覧</span></h3>
    <div class="ml-4">
    {% if user.customer_id %}
    {# 有料会員なら予約店舗を表示 #}
        {% if reservations %}
        <table class="table">
            <tr>
                <th>店舗</th>
                <th>予約日時</th>
                <th>予約人数</th>
                <th>共有事項</th>
                <th>操作</th>
            </tr>
            {% for reservation in reservations %}
                <tr>
                    <td>{{reservation.restaurant_id.name}}</td>
                    <td>{{reservation.reservation_datetime}}</td>
                    <td>{{reservation.number_of_persons}}</td>
                    <td>{{reservation.comment}}</td>
                    <td>
                        <form action="{% url 'nagoyameshi:reservation_delete' pk=reservation.pk %}" method="POST">
                            {% csrf_token %}

                            <button type="button" data-bs-toggle="modal" data-bs-target="#cancelConfirmModal" class="btn btn-primary btn-sm">取り消し</button>
                          
                            {# 確認モーダル #}
                            <div class="modal fade" id="cancelConfirmModal" tabindex="-1" aria-labelledby="cancelConfirmModalLabel" aria-hidden="true">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h2 class="modal-title fs-5" id="cancelConfirmModalLabel">予約の取り消し</h2>
                                            <button type="button" class="btn text-muted btn-close" data-bs-dismiss="modal" aria-label="Close"><i class="fas fa-window-close"></i></button>
                                        </div>
                                        <div class="modal-body">
                                            予約を取り消ししますか？
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">キャンセル</button>
                                            <button type="submit" class="btn btn-primary">確定</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </td>
                </tr>
            {% endfor %}
        </table>
        {% else %}
            <p>予約情報はまだありません。</p>
        {% endif %}
    
    {% else %}
    {# 無料会員なら有料会員登録に誘導 #}
    <p> <a href="{% url 'nagoyameshi:premium' %}">有料会員になる</a>と店舗を予約することができます。</p>
    </div>
    {% endif %}

</section>

{# ========== 会員情報 ========== #}
<section class="mb-5">
    <h3 class="mypage_section"><i class="fas fa-caret-right mr-2"></i><span>会員情報</span></h3>
    <div class="ml-4">
    <table class="table bg-white">
        <tr>
            <td>ニックネーム</td>
            <td>{{user.username}}</td>
        </tr>

        <tr>
            <td>メールアドレス</td>
            <td>
                {{user.email}}
                <span class="ml-3">
                    {% if user.email_verified %}
                        認証済み
                    {% else %}
                        <a href="{% url 'regenerate_token' %}">未認証</a>
                    {% endif %}
                </span>
            </td>
        </tr>

        <tr>
            <td>氏名</td>
            <td>
                {% if user.last_name and user.first_name %}
                    {{user.last_name}} {{user.first_name}}
                {% else %}
                    未登録
                {% endif %}
            </td>
        </tr>

        <tr>
            <td>電話番号</td>
            <td>
                {% if user.phone_number %}
                    {{user.phone_number}}
                {% else %}
                    未登録
                {% endif %}
            </td>
        </tr>

        <tr>
            <td>年齢</td>
            <td>
                {% if user.age %}
                    {{user.age}}
                {% else %}
                    未登録
                {% endif %}
            </td>
        </tr>
    </table>
    

    <a href="{% url 'user_update' %}">編集</a>
    </div>
</section>


{# ========== サブスクリプション ========== #}
<section class="mb-5">
    <h3 class="mypage_section"><i class="fas fa-caret-right mr-2"></i><span>サブスクリプション</span><i class="fa-solid fa-gem ml-2" style="color: #74C0FC;"></i></h3>
    <div class="ml-4">
    <p>
        月額300円でもっと便利に♪<br>
        有料会員になると、以下の特典を受けることができます！
    </p>
    <ul>
        <li>予約機能</li>
        <li>レビュー投稿機能</li>
        <li>お気に入り機能</li>
    </ul>
    <a href="{% url 'nagoyameshi:premium' %}" class="btn btn-primary">有料会員になる<i class="fa-solid fa-gem ml-2" style="color: #74C0FC;"></i></a>
    </div>
</section>


{# ========== ログアウト ========== #}
<section class="mb-5">
    <form action="{% url 'logout' %}" method="POST">
        {% csrf_token %}
        <button type="button" data-bs-toggle="modal" data-bs-target="#logoutModal" class="btn btn-link d-block mx-auto"> - ログアウト - </button>
                          
        {# ログアウト確認モーダル #}
        <div class="modal fade" id="logoutModal" tabindex="-1" aria-labelledby="logoutModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h2 class="modal-title fs-5" id="logoutModalLabel">ログアウト</h2>
                        <button type="button" class="btn text-muted btn-close" data-bs-dismiss="modal" aria-label="Close"><i class="fas fa-window-close"></i></button>
                    </div>
                    <div class="modal-body">
                        ログアウトしますか？
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">キャンセル</button>
                        <button type="submit" class="btn btn-primary">ログアウト</button>
                    </div>
                </div>
            </div>
        </div>

    </form>
</section>

</div>
</div>
{% endblock %}

templates/nagoyameshi/premium_active.html
{% extends "base.html" %}
{% load bootstrap %}
{% block title %}有料会員情報{% endblock %}

{% block content %}
<h1>有料会員情報</h1>


<h3>有料会員にご登録済みです。</h3>


<form action="{% url 'nagoyameshi:portal' %}" method="GET">
    <button type="submit">お支払情報の変更・解約</button>
</form>




{% endblock %}

templates/nagoyameshi/premium_inactive.html
{% extends "base.html" %}
{% load bootstrap %}
{% block title %}有料会員登録{% endblock %}

{% block content %}
<h1>有料会員登録</h1>

<div class="container">

    <div class="w-75 mx-auto">
    <h3>月額300円で以下の有料会員限定機能が利用可能になります。</h3>
    <ul>
        <li>店舗の予約機能</li>
        <li>レビュー投稿機能</li>
        <li>お気に入り機能機能</li>

    </ul>

    <form action="{% url 'nagoyameshi:checkout' %}" method="POST">
        {% csrf_token %}
        <button type="submit" class="btn btn-primary d-block mx-auto btn-lg my-4">有料会員登録<i class="fa-solid fa-gem ml-2" style="color: #74C0FC;"></i></button>
    </form>

    </div>
</div>

{% endblock %}

templates/nagoyameshi/reservation_form.html
{% extends "base.html" %}
{% load bootstrap %}
{% load static %}
{% block title %}予約フォーム{% endblock %}
{% block head %}
<link rel="stylesheet" href="{% static 'nagoyameshi/css/star_radio.css' %}">
{% endblock %}

{% block content %}
<h1>{{ restaurant.name }}へのご予約</h1>

<div class="container">

<form action="" method="POST" class="w-50 mx-auto my-3">
    {% csrf_token %}

    <table class="table">
        {# 予約日時 #}
        <tr>
            <td>ご予約日時</td>
            <td><input type="datetime-local" name="reservation_datetime" class="flatpicker w-50"></td>
        </tr>
        
        {# 予約人数 #}
        <tr>
            <td>人数</td>
            <td><input type="number" name="number_of_persons" class="w-50"></td>
        </tr>

        {# コメント #}
        <tr>
            <td>共有事項</td>
            <td><textarea name="comment" class="w-100"></textarea></td>
        </tr>
        

    </table>

    <button type="button" data-bs-toggle="modal" data-bs-target="#reservationConfirmModal" class="btn btn-primary btn-lg d-block mx-auto m-4">予約</button>
                          
    {# 確認モーダル #}
    <div class="modal fade" id="reservationConfirmModal" tabindex="-1" aria-labelledby="reservationConfirmModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h2 class="modal-title fs-5" id="reservationConfirmModalLabel">予約 </h2>
                    <button type="button" class="btn text-muted btn-close" data-bs-dismiss="modal" aria-label="Close"><i class="fas fa-window-close"></i></button>
                </div>
                <div class="modal-body">
                    本当に予約しますか？
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">キャンセル</button>
                    <button type="submit" class="btn btn-primary">確定</button>
                </div>
            </div>
        </div>
    </div>

</form>
</div>
{% endblock %}

{% block script %}
<script>
    flatpickr('.flatpicker', {
        locale: "ja",
        enableTime: true,
        minDate: 'today'
    });
</script>
{% endblock %}

templates/nagoyameshi/review_list.html
{% extends "base.html" %}
{% load bootstrap %}
{% block title %}{{ restaurant.name }}へのレビュー{% endblock %}

{% block content %}
<h1>{{ restaurant.name }}へのレビュー一覧</h1>

<div class="container">

<a href="{% url 'nagoyameshi:review_form' pk=restaurant.pk %}" class="btn btn-secondary d-block mx-auto my-4 w-25">
    <h3>
        レビューを投稿
        {% if not user.customer_id %}
            <i class="fa-solid fa-gem ml-1" style="color: #74C0FC;"></i>
        {% endif %}
    </h3>
</a>

<div>
{% for review in review_list %}
    <div class="border-top border-bottom px-4 py-3 w-75 mx-auto">
        
        {# === 星の数 === #}
        <div class="d-flex flex-row">
            {# 星の数 #}
            <h4>
                {% for i in review.number_of_stars_str.true_star  %}
                <i class="fa-solid fa-star text-warning"></i>
                {% endfor %}
                {% for i in review.number_of_stars_str.false_star  %}
                <i class="fa-solid fa-star text-muted"></i>
                {% endfor %}
            </h4>

            {# 来店日 #}
            <p class="d-block align-self-center my-0 mx-3">
                {{ review.visited_date }} 訪問
            </p>
        </div>


        {# ===　コメント　=== #}
        <p class="m-3">{{ review.comment }}</p>

        {# === フッター === #}
        <div class="review_footer d-flex flex-row w-100 align-items-center justify-content-end">

            {# ユーザー名 #}
            <p class="d-block align-self-center m-0">&mdash; &nbsp; {{ review.user_id.username }}</p>

            {# 投稿日 #}
            <p class="d-block align-self-center m-0">投稿日：{{ review.created_at }}</p>

            {# 編集ボタン #}
            {% if user.username == review.user_id.username %}
            <a href="{% url 'nagoyameshi:review_edit' pk=review.pk %}" class="ml-3">編集</a>

            {# 削除ボタン #}
            <form action="{% url 'nagoyameshi:review_delete' pk=review.pk %}" method="POST">
                {% csrf_token %}
                <button type="button" data-bs-toggle="modal" data-bs-target="#reviewDeleteConfirmModal" class="btn btn-link">削除</button>
                            
                {# 確認モーダル #}
                <div class="modal fade" id="reviewDeleteConfirmModal" tabindex="-1" aria-labelledby="reviewDeleteConfirmModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h2 class="modal-title fs-5" id="reviewDeleteConfirmModalLabel">レビュー削除 </h2>
                                <button type="button" class="btn text-muted btn-close" data-bs-dismiss="modal" aria-label="Close"><i class="fas fa-window-close"></i></button>
                            </div>
                            <div class="modal-body">
                                レビューを削除しますか？
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">キャンセル</button>
                                <button type="submit" class="btn btn-primary">確定</button>
                            </div>
                        </div>
                    </div>
                </div>

            </form>
            {% endif %}

            

        </div>
    </div>
{% endfor %}
</div>

</div>

{% endblock %}

templates/nagoyameshi/top.html
{% extends "base.html" %}
{% load static %}
{% block title %}店舗一覧{% endblock %}

{% block content %}
<h1 class="page_title">店舗一覧</h1>


<div class="container pb-5 px-2">


{# 店舗リストが空でない場合 #}
{% if restaurants %}

    <div class="row">
        {% for restaurant in restaurants %}
            <div class="col-lg-4  mb-4">
            <a href="{% url "nagoyameshi:restaurant_detail" pk=restaurant.pk%}" class="text-dark">
            <div class="card" style="width: 22rem; height: 31rem">
                <img src="{{ restaurant.image.url }}" class="card-img-top h-50" alt="">
                <div class="card-body position-relative">

                    {# 店名 #}
                    <h5 class="card-title">{{ restaurant.name }}</h5>

                    {# 星の数 #}
                    {% include "nagoyameshi/partials/star_average.html" with small=True %}

                    {# 予算 #}
                    <p>{{ restaurant.floor_price }} ~ {{ restaurant.maximum_price }} 円</p>

                    {# 説明文 #}
                    <p class="card-text">{{ restaurant.description }}</p>

                </div>

                
            </div>
            </a>
            </div>
        {% endfor %}
    </div>

{# 店舗リストが空の場合 #}
{% else %}
    <p>キーワードを含む店舗は見つかりませんでした。</p>

{% endif %}


</div>
{% endblock %}