config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('nagoyameshi.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

nagoyameshi/urls.py
from django.urls import path
from . import views

app_name = 'nagoyameshi'
urlpatterns = [
    path('', views.index, name='index'),
    path('top/', views.top, name='top'),
    path('restaurant/<int:pk>', views.restaurant_detail, name='restaurant_detail'),
    path('restaurant/review_list/<int:pk>', views.review_list, name='review_list'),
    path('restaurant/review_form/<int:pk>', views.review_form, name='review_form'),
    path('restaurant/review_edit/<int:pk>', views.review_edit, name='review_edit'),
    path('restaurant/review_delete/<int:pk>', views.review_delete, name='review_delete'),
    path('restaurant/reservation_form/<int:pk>', views.reservation_form, name='reservation_form'),
    path('restaurant/reservation_delete/<int:pk>', views.reservation_delete, name='reservation_delete'),
    path('mypage/', views.mypage, name='mypage'),

    # サブスク関連
    path("checkout/", views.checkout, name="checkout"),
    path("success/", views.success, name="success"),
    path("portal/", views.portal, name="portal"),
    path("premium/", views.premium, name="premium"),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}{% endblock %} - NAGOYAMESHI</title>
        <link rel="shortcut icon" href="{% static 'nagoyameshi/img/favicon.ico'%}"> 
        
        {# bootstrap読み込み #}
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous" defer></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" type="text/css">

        {# Google Fonts読み込み #}
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Train+One&display=swap" rel="stylesheet">
    
        {# flatpicker読み込み #}
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
        <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
        <script src="https://cdn.jsdelivr.net/npm/flatpickr/dist/l10n/ja.js"></script>

        {# css読み込み #}
        <link rel="stylesheet" href="{% static 'nagoyameshi/css/style.css' %}">

        {% block head %}{% endblock %}
    </head>

    <body>
        <header>

            {# ロゴ #}
            <a href="{% url 'nagoyameshi:index'%}" class="navbar-brand">
                <img src="{% static 'nagoyameshi/img/logo.png'%}" alt="ロゴ" class="">
                <p class="m-0">NAGOYAMESHI</p>
            </a>

            {# 検索フォーム #}
            <form action="{% url 'nagoyameshi:top' %}" method="GET" id="search_form" class="">


                <select name="category" id="" value="{{ request.GET.category }}" class="h-100">
                    <option value="">全て</option>
                    {% for category in CATEGORIES_LIST %}
                        <option value="{{ category.name }}" {% if category.name == request.GET.category %}selected{% endif%}>
                            {{category.name}}
                        </option>
                    {% endfor %}
                </select>
                <input type="text" name="keyword" value="{{ request.GET.keyword }}" class="h-100" placeholder="店名検索">
                <input type="number" name="floor_price" value="{{ request.GET.floor_price}}" class="h-100" placeholder="予算下限">
                <input type="number" name="maximum_price" value="{{ request.GET.maximum_price}}" class="h-100" placeholder="予算上限">
                <button type="submit" class="btn h-100"><i class="fas fa-search"></i></button>
 
            </form>

            {# navigation #}
            <div class="header_navigation">
                {# ユーザー名とログイン/ログアウトボタン #}
                {% if request.user.is_authenticated %}
                    {# ログイン済みの場合 #}
                    <a href="{% url 'nagoyameshi:mypage' %}" class="header_username">{{ user.username }}さん</a>
                    <a href="{% url 'nagoyameshi:mypage' %}">マイページ</a>
                    <form action="{% url 'logout' %}" method="POST">
                        {% csrf_token %}

                        <button type="button" data-bs-toggle="modal" data-bs-target="#logoutModal">ログアウト</button>
                          
                        {# ログアウト確認モーダル #}
                        <div class="modal fade" id="logoutModal" tabindex="-1" aria-labelledby="logoutModalLabel" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h2 class="modal-title fs-5" id="logoutModalLabel">ログアウト</h2>
                                        <button type="button" class="btn text-muted btn-close" data-bs-dismiss="modal" aria-label="Close"><i class="fas fa-window-close"></i></button>
                                    </div>
                                    <div class="modal-body">
                                        ログアウトしますか？
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">キャンセル</button>
                                        <button type="submit" class="btn btn-primary">ログアウト</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                          
                    </form>
                {% else %}
                    {# ログインしていない場合 #}
                    <a href="{% url 'signup' %}">会員登録</a>
                    <a href="{% url 'login' %}">ログイン</a>
                {% endif %}
            </div>

        </header>

        <main class="bg_color_main">
            {# メッセージ欄 #}
            <div class="notify_message_area">
                {% for message in messages %}
                <div class="notify_message notify_message_{{ message.tags }}">
                        <div class="notify_message_content">{{ message }}</div>
                        <div class="notify_message_delete"><i class="fas fa-times"></i></div>
                </div>
                {% endfor %}
            </div>

            {# 各ページのコンテンツ #}
            {% block content %}{% endblock %}
            

        </main>

        <footer class="d-flex flex-column justify-content-center">
            <a href="{% url 'nagoyameshi:top' %}" class="d-block text-center mb-1">NAGOYAMESHI</a>
            {% if request.user.is_authenticated %}
            <div class="text-center">
                <a href="{% url 'nagoyameshi:top' %}" class="mx-2">店舗一覧</a>
                <a href="{% url 'nagoyameshi:mypage' %}" class="mx-2">マイページ</a>
                <a href="{% url 'nagoyameshi:premium' %}" class="mx-2">サブスクリプション</a>
                <button type="button" data-bs-toggle="modal" data-bs-target="#logoutModal" class="btn btn-link">ログアウト</button>
            </div>
            {% endif %}
        </footer>

        {# JavaScriptの読み込み #}
        <script src="{% static 'nagoyameshi/js/script.js' %}"></script>

        {% block script %}{% endblock %}
    </body>
</html>